/**
 * Api Key Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package pt.ipca.doamais.api.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Beneficiario {
  
  @SerializedName("contacto")
  private String contacto = null;
  @SerializedName("dimensaoAgregado")
  private Integer dimensaoAgregado = null;
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("nacionalidade")
  private String nacionalidade = null;
  @SerializedName("nomeRepresentante")
  private String nomeRepresentante = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getContacto() {
    return contacto;
  }
  public void setContacto(String contacto) {
    this.contacto = contacto;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDimensaoAgregado() {
    return dimensaoAgregado;
  }
  public void setDimensaoAgregado(Integer dimensaoAgregado) {
    this.dimensaoAgregado = dimensaoAgregado;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNacionalidade() {
    return nacionalidade;
  }
  public void setNacionalidade(String nacionalidade) {
    this.nacionalidade = nacionalidade;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNomeRepresentante() {
    return nomeRepresentante;
  }
  public void setNomeRepresentante(String nomeRepresentante) {
    this.nomeRepresentante = nomeRepresentante;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Beneficiario beneficiario = (Beneficiario) o;
    return (this.contacto == null ? beneficiario.contacto == null : this.contacto.equals(beneficiario.contacto)) &&
        (this.dimensaoAgregado == null ? beneficiario.dimensaoAgregado == null : this.dimensaoAgregado.equals(beneficiario.dimensaoAgregado)) &&
        (this.id == null ? beneficiario.id == null : this.id.equals(beneficiario.id)) &&
        (this.nacionalidade == null ? beneficiario.nacionalidade == null : this.nacionalidade.equals(beneficiario.nacionalidade)) &&
        (this.nomeRepresentante == null ? beneficiario.nomeRepresentante == null : this.nomeRepresentante.equals(beneficiario.nomeRepresentante));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.contacto == null ? 0: this.contacto.hashCode());
    result = 31 * result + (this.dimensaoAgregado == null ? 0: this.dimensaoAgregado.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.nacionalidade == null ? 0: this.nacionalidade.hashCode());
    result = 31 * result + (this.nomeRepresentante == null ? 0: this.nomeRepresentante.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Beneficiario {\n");
    
    sb.append("  contacto: ").append(contacto).append("\n");
    sb.append("  dimensaoAgregado: ").append(dimensaoAgregado).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  nacionalidade: ").append(nacionalidade).append("\n");
    sb.append("  nomeRepresentante: ").append(nomeRepresentante).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
