/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pt.ipca.doamais.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tipoBens 
 * @param id 
 * @param beneficiarioId 
 * @param dataLevantamento 
 * @param createdBy 
 */


data class Levantamento (

    @Json(name = "tipoBens")
    val tipoBens: kotlin.String?,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "beneficiarioId")
    val beneficiarioId: kotlin.Int? = null,

    @Json(name = "dataLevantamento")
    val dataLevantamento: java.time.OffsetDateTime? = null,

    @Json(name = "createdBy")
    val createdBy: kotlin.Int? = null

) {


}

