/**
 * Api Key Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package pt.ipca.doamais.api.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Levantamento {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("beneficiarioId")
  private Integer beneficiarioId = null;
  @SerializedName("tipoBens")
  private String tipoBens = null;
  @SerializedName("dataLevantamento")
  private Date dataLevantamento = null;
  @SerializedName("createdBy")
  private Integer createdBy = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getBeneficiarioId() {
    return beneficiarioId;
  }
  public void setBeneficiarioId(Integer beneficiarioId) {
    this.beneficiarioId = beneficiarioId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTipoBens() {
    return tipoBens;
  }
  public void setTipoBens(String tipoBens) {
    this.tipoBens = tipoBens;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDataLevantamento() {
    return dataLevantamento;
  }
  public void setDataLevantamento(Date dataLevantamento) {
    this.dataLevantamento = dataLevantamento;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCreatedBy() {
    return createdBy;
  }
  public void setCreatedBy(Integer createdBy) {
    this.createdBy = createdBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Levantamento levantamento = (Levantamento) o;
    return (this.id == null ? levantamento.id == null : this.id.equals(levantamento.id)) &&
        (this.beneficiarioId == null ? levantamento.beneficiarioId == null : this.beneficiarioId.equals(levantamento.beneficiarioId)) &&
        (this.tipoBens == null ? levantamento.tipoBens == null : this.tipoBens.equals(levantamento.tipoBens)) &&
        (this.dataLevantamento == null ? levantamento.dataLevantamento == null : this.dataLevantamento.equals(levantamento.dataLevantamento)) &&
        (this.createdBy == null ? levantamento.createdBy == null : this.createdBy.equals(levantamento.createdBy));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.beneficiarioId == null ? 0: this.beneficiarioId.hashCode());
    result = 31 * result + (this.tipoBens == null ? 0: this.tipoBens.hashCode());
    result = 31 * result + (this.dataLevantamento == null ? 0: this.dataLevantamento.hashCode());
    result = 31 * result + (this.createdBy == null ? 0: this.createdBy.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Levantamento {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  beneficiarioId: ").append(beneficiarioId).append("\n");
    sb.append("  tipoBens: ").append(tipoBens).append("\n");
    sb.append("  dataLevantamento: ").append(dataLevantamento).append("\n");
    sb.append("  createdBy: ").append(createdBy).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
