/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pt.ipca.doamais.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param tarefas 
 * @param time 
 * @param userId 
 */


data class Turno (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "tarefas")
    val tarefas: kotlin.String? = null,

    @Json(name = "time")
    val time: java.time.OffsetDateTime? = null,

    @Json(name = "userId")
    val userId: kotlin.Int? = null

) {


}

