/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pt.ipca.doamais.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param name 
 * @param role 
 * @param id 
 * @param password 
 * @param createdOn 
 */


data class User (

    @Json(name = "username")
    val username: kotlin.String?,

    @Json(name = "name")
    val name: kotlin.String?,

    @Json(name = "role")
    val role: kotlin.String?,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "password")
    val password: kotlin.String? = null,

    @Json(name = "createdOn")
    val createdOn: java.time.OffsetDateTime? = null

) {


}

