/**
 * Api Key Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package pt.ipca.doamais.api.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Visita {
  
  @SerializedName("id")
  private Integer id = null;
  @SerializedName("beneficiarioId")
  private Integer beneficiarioId = null;
  @SerializedName("date")
  private Date date = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getBeneficiarioId() {
    return beneficiarioId;
  }
  public void setBeneficiarioId(Integer beneficiarioId) {
    this.beneficiarioId = beneficiarioId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getDate() {
    return date;
  }
  public void setDate(Date date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Visita visita = (Visita) o;
    return (this.id == null ? visita.id == null : this.id.equals(visita.id)) &&
        (this.beneficiarioId == null ? visita.beneficiarioId == null : this.beneficiarioId.equals(visita.beneficiarioId)) &&
        (this.date == null ? visita.date == null : this.date.equals(visita.date));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.beneficiarioId == null ? 0: this.beneficiarioId.hashCode());
    result = 31 * result + (this.date == null ? 0: this.date.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Visita {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  beneficiarioId: ").append(beneficiarioId).append("\n");
    sb.append("  date: ").append(date).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
