/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pt.ipca.doamais.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param beneficiarioId 
 * @param date 
 */


data class Visita (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "beneficiarioId")
    val beneficiarioId: kotlin.Int? = null,

    @Json(name = "date")
    val date: java.time.OffsetDateTime? = null

) {


}

